spring.application.name=jpa_lab
spring.datasource.url=jdbc:sqlserver://localhost;database=hrdb;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update