spring.application.name=jpa_lab
spring.datasource.url=jdbc:sqlserver://(localdb)\\mssqllocaldb;database=springlab;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
